services:
  - type: web
    name: hrms-lite-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: DATABASE_URL
        value: sqlite:///instance/hrms_lite.db
